NetsBlox/Snap--Build-Your-Own-Blocks

gui.js
This allows the server to inject javascript to manually set the server url. This is important for alternative clients like mobile apps in which the files are not served from the target server.
=> Single source of truth for server address

test/snap-driver.js
Fixes #692, now drags are from top left, test that was failing before now passes.
=> Driver dragAndDrop now grabs from top left by default Fix #692

netsblox.js
The unnecessary clearing of the role was resulting in the project getting out-of-sync with the version on the server. As a result, it was not able to determine the number of occupants at the role.
=> Removed unnecessary clearing role. Fixes #728

gui.js, objects.js
This simply adds support for detecting the correct scripts when starting keyboard editing mode. It does not stop keyboard editing until the user actually presses escape and the script cursor will keep the keyboard focus until then, too.
=> Added support for editing custom blocks with the keyboard. Fixes #703

store.js
snap's `xml.js` replaces this character with `&lt;`
=> "<" serialization in event arguments fixes #732

blocks.js, test/messages.spec.js, websockets.js
adds a number next to message listener hatblocks showing the messages in the queue with support for clearing the queue. 
This should allow us to remove the need for throttling sending of the messages on the server and might eliminate the need for `stop` rpcs in some of the services.
=> message queue counter and control UI Fixes #652

threads-ext.js
This is a quick fix that gives correct output for the translation RPC.
#740 has a picture of the incorrect behavior.
=> Unicode responses for RPCs Fix #740

threads-ext.js
- goes with https://github.com/NetsBlox/NetsBlox/pull/2286
- this sort of rate limiting is only on the client side and thus could be avoided by the user therefore only protecting against unintentional bursts of messages
=> per block message send rate limit. Fixes #662

netsblox.js
other ways of showing it could be to:
- append it 
- have it scroll
- NetsBlox [projectname rol]
since the page favicon will indicate that it's from NetsBlox I'll prepend the project name instead of appending it
=> show the open project name in page title fixes #785

blocks-ext.js, blocks.js, gui.js, index.dev.html, index.dot, main.js, utils.js
- caches RPC names and method signatures reducing the number of synchronous XHR request on the main thread
- adds a new `utils.js` file.
=> cached sync xhr requests for rpc method signatures

threads-ext.js
use asArray() on Snap lists before sending the message to the server to ensure consistency
=> send message linked list fixes #792

actions.js
Previously, I had assumed that `PrototypeHatMorph`s did not have child inputs and only had next blocks (and the input spec, of course). This PR fixes the addressing to support editing child inputs (such as the list input with the block variables) for custom blocks.
=> Enabled creating block variables. Fixes #802

blocks-ext.js
This PR clears the inputs and next block before displaying the block in the help message.
=> Clear RPC block inputs and next blocks in help msg. Fixes #794

embedded-api.js, gui-ext.js, netsblox.js, test/ide.spec.js, test/index.html, utils.js, websockets.js
This PR adds a wrapper for the embedded NetsBlox API. This is hosted in the repo and can be included by including the file in a script tag in the parent application's html:
```html
<script src="URL_OF_NETSBLOX_DEPLOYMENT/embedded-api.js"></script>
```
This will define `EmbeddedNetsBloxAPI` as a global which can be initialized with:
```javascript
const api = new EmbeddedNetsBloxAPI(iframeElementWithNetsBlox);
```
=> Add EmbeddedNetsBloxAPI wrapper and getProjectXML. Closes #986

objects.js
This PR adds "hide..." as a convenience to the context menu for the variable watcher. (It wasn't obvious to me why an empty "hide variable" block should remove all temporaries. This functionality has not been modified but simply adds another approach that is more intuitive imo.)
=> Hide variable watchers from context menu. Closes #1017

test/index.html, test/undo.spec.js
The goal of this PR is to improve the test coverage. This does not include fixes for the issues since this would make the PR much larger and the goal is to cover some of the big gaps in the test suite (not get sidetracked by fixing individual ones just yet). 
This PR adds a number of different (needed) tests to the client. These include:
=> Add undo tests for reverting block positions

src/gui.js, src/netsblox.js, src/netscloud.js
This PR adds support for linking Snap! accounts to NetsBlox accounts and using Snap! or authentication.
This adds a "Login with Snap!" option:
This will log the user in with the given Snap! credentials. If there is no existing linked NetsBlox account, one will be created.
After logging in, the cloud menu will provide an option for linking/unlinking a Snap account:
=> Add support for linking Snap! accounts to netsblox. Closes #1049

src/actions.js, test/multi/collaboration.spec.js, test/multi/index.html, test/snap-driver.js
This also makes sure the client has the correct state on the server before requesting missing actions.
=> Add more collaboration tests. Closes #1095

src/objects-ext.js, src/objects.js, src/threads-ext.js
This adds a block called `image of _` which receives a Snap! object (can select from dropdown or with the pre-existing `object _` block), renders it on a canvas, and converts it to a costume. Motivation for this was for use in PhoneIoT, but there are probably some other applications. The code I used for this was based on the `save _ as costume named _` block from the newer versions of Snap!. They made that dev-only, I assume because it proliferates costumes which have to be saved along with the project. The block added in this PR, however, does not save it; so I think this would be ok in user mode (as far as I'm aware, it's no worse than an RPC that returns an image). I don't know where help info is added, but I think the usage is pretty self-explanatory given that the only input is a …
=> added image of object block

src/extensions.js, src/objects.js, test/extensions.spec.js
This updates the extension API to make the palette contents explicit. This allows users to add new blocks of existing types and define palette contents for specific sprites/stages/etc.
=> Add support for sprite/stage specific palette contents. Close #1233

src/blocks.js
This fixes issue [3171](https://github.com/NetsBlox/NetsBlox/issues/3171) from the NetsBlox repo. Turns out it was not only exclusively on the client side, but was also a one-line-fix. The issue was getting the ide object from a block morph while it was being dragged returns null.
This is potentially an issue for other blocks, but I think it has to be triggered by external code during a drag, meaning hat blocks should be the only suspects. Also, the problem code was only in updating the message queue display, so I'm thinking the others are all ok.
=> update readout fix

src/blocks-ext.js
Closes #1247. This PR adds links at the bottom of the RPC help menu that go to the official documentation. The links already have the correct tag to jump to the right function on the page, but they seem to be ignored when clicked (so it'll just go to the right _page_ at the moment).
=> RPC help links to official docs

embedded-api.js, src/actions.js, src/gui-ext.js, src/gui.js, test/ide.spec.js
This adds support for adding custom events to a project and listening to them via the embedded API. Here is an example:
In a custom block:
```javascript
const process = arguments[0];  // The last argument to a JS block is always the process itself
const events = process.receiver.parentThatIsA(IDE_Morph).events;
events.dispatchEvent(new CustomBlock('myCustomEvent', {detail: {someDataICareAbout}});
```
From the embedded API (assuming the instance is named `api`):
```javascript
api.addEventListener('myCustomEvent', event => console.log(event.detail.someDataICareAbout));
```
=> Add support for defining custom events. Closes #1266

src/blocks-ext.js, src/blocks.js, src/utils.js
This PR changes RPC input slots to use argument metadata along with [base type](https://github.com/NetsBlox/NetsBlox/pull/3213) info to make the inputs "strongly-typed". Currently, this just means numeric values get round slots that only accept number characters when typing, and enum inputs become a dropdown (which is the more interesting one).
Note: this requires [the base types PR](https://github.com/NetsBlox/NetsBlox/pull/3213) in order to work.
=> Typed RPC Input Slots

src/extensions.js, src/gui-ext.js, src/netsblox.js, src/room.js, test/extensions.spec.js
Adding `onOpenRole` to an extension will define logic that is invoked when a role is opened. `onNewProject` is invoked only when creating a new project (after which `onOpenRole` will be called).
=> Add onOpenRole and onNewProject handlers for extensions. Closes #1230

src/gui.js
This moves the default trusted sources into a list where additional trusted extension sources are easier to add.
Close #1280
=> Change isAutoTrusted check to use list of sources

src/actions.js, src/extensions.js, src/gui-ext.js, src/room.js
Close #1277 
The original code tried to run `onOpenRole` after each call to `SnapActions.openProject`, but some cases were missed. This version runs `onOpenRole` any time a new project/role is opened including the default roles of projects.
=> Run extension onOpenRole in all changes of role

src/cloud.js
@brollb In looking for the project open bug in the mobile app, I found the cause was that the `private` action for the client simply wasn't working. That not loading means the project loaded events are never fired, which causes the infinite loading screen bug in the app.
After any needed changes, I can apply the final PR to the mobile app and rebuild/publish.
=> getProjectByName fix

src/threads.js
Closes #1292. Turns out the issue was that the foreach loop was adding auto-insert variables like map does, where it takes the iterator item and inserts it into any empty slot. This was overriding rpc default values since they weren't empty at the time of invocation. This PR fixes this by removing that auto-fill behavior.
**Technically, this is a breaking change from Snap!**, but frankly I think it was a crazy idea for them to have that feature in the first place - it defeats the point of having an upvar and behaves differently than other Snap! primitives like the normal integer-based for loop.
=> fix rpc defaults in foreach

src/gui.js, src/netsblox.js, src/store.js
This PR:
- updates the project loading function to be async and resolve only after pentrails have been completely loaded
- unifies the project loading fns from netsblox.js, gui.js
- renames the old version of the project loading fn to have the `Sync` suffix. It's a little misleading since it just doesn't check if the project is completely loaded (ie, how it works before this PR)
=> Wait for stage pentrails to be loaded b4 runScripts. Fix #1303

src/threads-ext.js, src/threads.js, src/utils.js
Closes #1310. Fixes a CORS issue with some websites that don't allow custom headers by only adding the `X-Source` header from #1297 if the request is going to the `netsblox.org` domain.
=> 1310 CORS Issue X-Source Header

privacy.html
Removes references to Google Analytics from the privacy page (`/privacy.html`). At this point, some Google Analytics code is still present, but only if an environment variable is set with a valid key; we no longer define said variable, so it is disabled.
_Also normalizes some indent and `<p>` inconsistencies in the html file._
=> Remove Google Analytics from Privacy

src/blocks-ext.js
Fix #1261 
This removes a check in `HintInputSlotMorph.prototype.changed` for the text displayed matching the hint text making the slot considered empty, instead relying on the check in `HintInputSlotMorph.prototype.setContents` for the slot actually being empty. 
For example, it is now possible to name a CloudVariables variable "name" and/or give it the value "value".
=> Remove empty check based on matching hint

src/objects-ext.js, src/threads-ext.js
Fix #1314 
Is there something better than `null` we could use for "no RPC error"?
=> Set default for rpcError

src/objects.js
@brollb Fixes loading projects with old binary sum/product. Was just missing a block meta entry from the previous refactor (apparently I replaced the old entries instead of adding new ones, since I thought that was just for the blocks palette).
=> fix loading binary sum/product

src/blocks-ext.js, src/messages.js
Close #1326 
Includes fix for `name` field and some minor improvements. The dialog now tells you when you didn't specify a name instead of closing immediately, the (functionless?) handle on the dialog is removed, and the name field has its initial hint text display correctly.
=> Fix message type creation dialog

src/room.js
This re-opens the room name changing dialog when a room name is rejected, so the user has a chance to fix it without retyping the whole thing.
=> Change how rejected room/role names are handled in UI

src/blocks.js
@brollb In #1320 I merged some changes for vanilla labeled parts, but didn't think to test extensions. This just adds a little bridge between the old and new formats to get everything working again without having to change anything else.
=> ext label parts hotfix

src/extensions.js, src/gui-ext.js, test/extensions.spec.js
Close #1340 
This allows extensions to optionally provide a list of toggle-able settings to be added to the menu.
@brollb Should this be called something different from "Options" in the menu, e.g. "Settings", "Preferences"? Where should the structure be documented?
=> Extension preferences

src/gui.js
This uses the internal project state (private, public, pending approval) to set the `public` flag used to bold the project names for the user.
=> Set public flag based on the project state. Fix #1371

src/blocks.js
@brollb Closes #1365. Looks like `httprt` input type was lost in the last input type refactor.
=> add missing httprt input type

src/blocks.js
This adds a guard to `snapTarget` to make sure the parent is a `ScriptsMorph`. This is a backport of https://github.com/jmoenig/Snap/blob/master/src/blocks.js#L7242-L7244
=> Add guard against non-ScriptsMorph parents. Fix #1421

src/gui-ext.js, src/gui.js, src/netsblox.js, src/room.js, test/gui.spec.js, test/snap-driver.js, test/utils.js
This PR refactors URL parameters to make them easier to test and reason about. I am also planning on converting all hash params to querystring params on load so they are normalized. Hopefully this results in more odd edge-case behavior.
- refactor URL param parsing to own function
- Refactoring URL params to individual classes
- Refactor url params to be more easily testable
=> URL parameter refactor

src/netsblox.js, src/room.js
This was causing media not to be loaded since the dropped text was actually
the incorrect format - they needed to be wrapped in <snapdata></snapdata>.
This is handled correctly in the initial load in `rawLoadCloudRole`
=> Remove redundant loading logic on move to role

src/gui.js, src/room.js
This also removes a little bit of dead code that isn't used anywhere.
=> Remove leading/trailing spaces in role/project names. Fix #1450

src/gui.js
Removing this one line fixes the issue of the scrolling menu in the open/save dialogs moving when you select something lower in the list (which made double-clicking open something else than you intended). I couldn't find any side-effects of it, the item is still highlighted and double-clicking or clicking open worked as expected.
=> Fix scroll position after click in open/save dialogs

src/morphic.js
Tested, browser open dialog no longer opens.
=> Prevent browser file open dialog from being triggered on ctrl/command+O

src/blocks.js, src/extensions.js, src/gui.js, src/objects.js
Adds `isSupported`, allowing extensions to decline to load before their constructor is run (optionally providing a message).
Adds custom context menus to pretty much every UI element that has context menus.
=> More extension features

src/gui-ext.js
Close #1513 
May need a bit of testing in case there's a case where this isn't preferred. It seems to work fine in appMode, embedMode, etc.
=> Focus morphic keyboard handler instead of canvas

src/gui.js, src/objects.js
Adds an experimental voice search button to the search-mode blocks palette on browsers that support it (chrome does, others are spotty, but NetsBlox itself is spotty on others anyway).
It works fairly well, but down the road we'll probably want special rules to fix things like "plus" instead of "+". But that's a problem we could address at the search level, rather than the voice recognition level (i.e., maybe we make searching in general way fuzzier so that "+", "add", "plus", and "sum" all match the add block, etc.).
=> add voice search

src/objects.js
Looks like #1504 broke the play note block because it was name shadowing the `Note` type. I've renamed this to `XmlNote` and fixed all (obvious) references to use the new name.
=> fix note name shadowing

src/extensions.js, src/gui-ext.js, src/gui.js
Adds a mechanism for load-by-default extensions. Extensions in the url will override default extensions, with the deduplicating logic being the file name from the extension url (either `<name>/index.js` or `<name>.js`). There's also now a `noDefaultExtensions` url flag to opt out for testing.
BeatBlox is now marked as a default extension.
=> default extensions

src/extensions.js, src/objects.js
Extensions can now add buttons to the palette. They are defined by an async function. If they return a value, it must be of form `{ label: action,... }`, which is displayed as a dropdown menu on the button (similar to the var/msg deletion buttons). This also allows sub-menus by giving another menu object in place of an action.
=> extension buttons

src/extensions.js, src/objects.js
Adds a large space `'='` to the start of each extension's block list in each category. Also fixes Snap!'s palette generator to skip leading spacers (needed for new categories like music that are exclusively populated by extensions).
=> separate blocks from different extensions
