simple-collab.js

changed to `prepareToBeGrabbed`

Changed the delete ui update method. Fixes #4

---

actions.js

Also clear the move target info on position changed

Register block after moved. Fixes #16

---

actions.js

This allows the user to still edit the project and work w/o
websocket support

Set user to leader if no websocket connection. Fixes #21

---

actions.js

Also suppressed block id reassignment on initial load

Changed initial load block id assign to unique. Fixes #170

---

room.js

Added basic message inspection capabilities for primitive data types. In the future, I will need to add support for inspecting messages containing more complex forms of data.

Added basic msg inspection capabilities. Closes #446

---

actions.js
blocks.js
gui.js
objects.js
store.js
undo.js

This adds "user actions" to `SnapActions`. These complement the current "project actions". Project actions represent actions performed on the project content whereas the user actions are tracking just the user behavior (that doesn't modify the project).

Added "user actions" logging. Closes #429

---

netscloud.js
room.js

since it's now handled on the server

removed onLogin and onPassiveLogin

---

gui-ext.js
netsblox.js
netscloud.js
room.js

Saving all the roles at once could sometimes result in data loss. Although not often, it is easier to make saving more explicit and give the user more control over when the project is saved.

Updated save to only save the current role. Closes #527

---

objects.js

These were removed during a refactor accidently.

Added the report latitude, longitude, username blocks. Fixes #561

---

gui-ext.js
netsblox.js
netscloud.js
test/multi/collaboration.spec.js
test/multi/index.html
test/snap-driver.js

This also fixes some issues with https://github.com/NetsBlox/NetsBlox/issues/2108

Updated joinActiveProject to use ID. Closes #622

---

netscloud.js
room.js
websockets.js

Related to https://github.com/NetsBlox/NetsBlox/issues/2144

Moved add/rename/clone role to REST. Closes #645

---

test/ws-monkey.js

regenerates a new profile each time a profile is played

multiple profiles for infinite/ongoing WebSocket monkey mode.

---

test/manual/main.js

Also removed auto login "feature"

Include the hash/querystring in iframe url. Fixes #689

---

blocks.js
byob.js
gui.js
objects.js

updated script pic hint text Fixes #655

---

index.dev.html
index.dot
on-message.js

I believe that Corey has talked with you about my work in connecting his web gallery software to NetsBlox.  This was accomplished by me forking Snap and making these changes to it, which I will now explain.
The "import-blocks" handler handles a parent frame trying to import serialized blocks (essentially, the contents of the `.xml` file that comes out of the "File > Export project" menu item) into NetsBlox.  It's fairly simple.
The "set-variable" handler allows us to set some JavaScript variables from the parent frame that we can then read from within the JS code in a custom JavaScript block.  We use this in the gallery, since the gallery sets its "session ID" (essentially, class period ID) in the URL hash.  This tells the gallery which bucket up student uploads it should be uploading to …

`postMessage` support

---

index.dev.html
index.dot

Dispatches "ideLoaded" event when IDE morph is initialized. If code depends on ide being loaded it can listen for this event

"ideLoaded" event dispatcher as an onload hook

---

blocks.js

since client code can't be transpiled due to potential merge conflicts it has have backward compatibility

removed leftover const keyword

---

README.md
index.dev.html

it also fixes the issue with index.dev.html not working

Remote server connection for client only setups Fixes #745

---

blocks.js
gui.js

adds a button to toggle single stepping.
two  commits were cherry-picked* from snap

add single stepping button fixes #750

---

threads-ext.js

rate limiting now acknowledges turbo mode vs normal mode

Messaging rate limit optimization (turbo)

---

threads-ext.js

removed rate limiting from affecting the normal (non-turbo) mode

messaging rate limiting reduced to turbo

---

netsblox.js
objects.js

the search can be activated by
1. activating search (ctrl+f) 
2. shift + click on the left panel
3. type in part of the block spec
the search could use some optimization and caching.
for example, skip re-searching custom blocks

block locater

---

netsblox.js
objects.js

count and merge duplicate output lines
min length query limit: 3 chars

block finder enhancements

---

actions.js

This is a minor refactor for clarity (and reduces some code duplication) in `onMoveBlock`

Decreased code duplication and side effects when deserializing target

---

gui.js
lists.js
morphic.js
netsblox.js
objects.js
threads.js

Add import/export csv, json, and text. Closes #811

---

threads-ext.js

Blocking https://github.com/NetsBlox/NetsBlox/issues/2487

Flush serializer btwn objects. Fixes #819

---

index.dot

This manually adds the version to the js path. This should be updated on subsequent releases.

Add version in js path query string. Closes #876

---

gui-ext.js
gui.js
test/ide.spec.js

This PR adds support for a basic public API for use with NetsBlox embedded as an iframe in a larger application. Thanks, @TheBizzle for your work in #735 (which this is based almost entirely off of!).

Add embedded API for netsblox use in iframe. Closes #927

---

test/generative/generative-tester.js

This adds many actions using SnapActions to the generative testing tools (essentially simulating a collaborative user).

Add more actions to generative testing tools. Closes #915

---

blocks-ext.js
index.dev.html
index.dot
netsblox.js
services.js
threads-ext.js

There are a couple more things that would be good to add:

Add basic support for multiple services servers. Closes #970

---

cloud.js
gui-ext.js
gui.js
netsblox.js
netscloud.js
test/index.html
test/project-dialog.spec.js
test/save.spec.js
test/snap-driver.js
test/utils.js

This depends on https://github.com/NetsBlox/NetsBlox/pull/2794

Refactor ProjectDialogMorph. Closes #991

---

src/actions.js
src/objects.js
test/actions.spec.js

This also contains a minor fix to another failing test.

Don't record toggle action in addVariable. Fixes #1131

---

src/gui.js
test/ide.spec.js

This adds the ability to set variables using a querystring parameter, `setVariable`. If the variable name doesn't exist, it will be created.
An example: http://localhost:5000/?action=example&ProjectName=Movies&noRun&editMode&setVariable=score%3D1000

Add setVariable URL param. Closes #1194

---

src/gui.js
test/blocks.spec.js

This still needs an automated test but otherwise should be good to go.

Clear block ID and pick up imported script immediately. Fixes #1242

---

src/extensions.js
src/gui.js

- Code to fix missing default value in extension blocks.
- Ability to hide categories with Shift Click.

Added default values to extensions. Added ability to hide categories

---

src/gui.js
src/netsblox.js
src/widgets.js

Reverts NetsBlox/Snap--Build-Your-Own-Blocks#1283

Revert "Disallow setting password on signup. Closes #1282"

---

src/gui.js

Fix #1317 
Needs a little testing to make sure there aren't any undesired side effects, but it does make the blocks appear when loading from a share link.

Load extensions before presenting project

---

src/gui.js

Prevent dragging message type blocks into sprites

---

src/gui.js

Error message for extension loading failure

---

src/cloud.js
src/gui.js
src/netsblox.js

Set password on account creation. Close #1332

Set password on account creation. Close #1332

---

src/blocks.js

Keys Menu Fix

---

src/blocks-ext.js

@brollb Add support for the special `global` category. This can be merged in without issue, as it doesn't do anything different unless `global` is present as a category.

support global category

---

src/store.js

Close #1316 
@dragazo Is this how you envisioned it? For example:
```
<block collabId="item_-1_2" s="getJSFromRPCStruct" inputNames="name,password">
<l>CloudVariables</l>
<l>getVariable</l>
<l>test</l>
<l></l>
</block>
```

Add RPC input names in XML output

---

src/websockets.js

If a project isn't found on reconnect, this takes the following action:
- re-imports it if it only has a single role
- reloads the page if guest user with multiple roles (as they must be viewing a public project or example)
- notifies the user of data loss and recommends saving in the future (the least ideal situation)

Try re-importing the project if unsaved. Fix #1374

---

src/gui.js
src/netsblox.js

- Update calls to update URL qs; publish project
- Use the correct owner when updating the URL. Fix #1378
- update submodule for updated client

Fix URL params for public, shared projects. Fix #1378

---

src/actions.js
src/extensions.js
src/gui.js
src/objects.js
src/threads.js
test/extensions.spec.js

Close #1384
Currently this adds onRunScripts, onStopAllScripts, onPauseAll, onResumeAll, onNewSprite, and onSetStageSize events to extensions.

Additional Extension Features

---

src/services.js
src/store.js

Get RPC method args list more reliably

---

src/gui-ext.js

Fix error loading extensions

---

src/threads-ext.js
test/index.html
test/threads.spec.js

- Add fix for resolving local addresses
- remove .only

resolve address fix

---

src/services.js

Close #1454
@brollb Is 2.5 seconds too short/long for you?

Add timeout to services fetch

---

src/blocks-ext.js

Use same fallback to get IDE inside custom block in more cases

---

utils/serve.js

This should make development easier since the cloud can then be swapped
out in a modular fashion like the browser code.

Configure the cloud to connect to via qs

---

src/gui-ext.js

This fixes the issue described in https://github.com/NetsBlox/Snap--Build-Your-Own-Blocks/pull/1472#issue-2019623449

Place palette after setting size

---

utils/minify.js

- change formatting for minify script
- Check if the cloud submodule is potentially out of sync

Warn if cloud submodule is possibly out of sync

---

src/gui.js
src/objects.js

This allows MUSIC XML files to be uploaded as projects in NetsBlox. The code is sloppier than I would like it to be. I will refactor it once the demos have been submitted.

Musicxml handling

---

src/objects.js

Get pen color

---

src/gui.js

Check if extensions should be shown in refreshIDE

---

src/blocks.js

fix shadow smear and undefined slot bug

---

utils/serve.js

fix crashes

---

src/room.js
src/websockets.js

Closes #1524. I don't wanna touch cloud just for this, so small client-side hax.

no invite self popup

---

HISTORY.md
src/blocks.js
src/gui.js
src/objects.js
src/threads.js

This PR fixes the broken 'set rgba' block. This pr cherry-picked 3 commits from the snap repo (fd25896, 361cbe6, and 299405d) to fix the block

fix set rgba block

---

src/extensions.js
src/gui-ext.js
src/gui.js

Extension menu is now always visible and minimally has an `Import...` submenu for dynamically loading official extensions.
Also refactors the menu-generating code to omit empty sub-menus.

extension button refactor
